// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://euetvbdrtjrvlrptirgu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV1ZXR2YmRydGpydmxycHRpcmd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3NjE5MDEsImV4cCI6MjA3MzMzNzkwMX0.jeGNbCr2ZaZ9AzGHg-SnVKLnVUbyoE2Bx3_ZqLJoCZk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});